#name: EAS Build Preview
#
#on:
#  workflow_dispatch:
#  push:
#    branches:
#      - main
#    paths-ignore:
#      - '**/*.md'
#      - '.github/**'
#      - 'docs/**'
#
#  pull_request:
#    branches:
#      - main
#    types: [opened, synchronize]
#    paths-ignore:
#      - '**/*.md'
#      - '.github/**'
#      - 'docs/**'
#
#jobs:
#  build:
#    name: Build Preview APK
#    runs-on: ubuntu-latest
#    permissions:
#      contents: read
#      issues: write
#      pull-requests: write
#    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
#
#    steps:
#      - name: Check for EXPO_TOKEN
#        run: |
#          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
#            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets."
#            exit 1
#          fi
#
#      - name: Checkout repository
#        uses: actions/checkout@v4
#
#      - name: Setup Node.js
#        uses: actions/setup-node@v4
#        with:
#          node-version: '20.x'
#          cache: 'npm'
#
#      - name: Setup EAS
#        uses: expo/expo-github-action@v8
#        with:
#          eas-version: latest
#          token: ${{ secrets.EXPO_TOKEN }}
#
#      - name: Install dependencies
#        run: npm ci
#
#      - name: Run linting
#        run: npm run lint
#
#      - name: Build on EAS
#        run: eas build --platform android --profile preview --non-interactive --no-wait
